### ISSUE TITLE
paper 1.21

### ISSUE THREAD

**Issue by Incluuu** [TeamVK/CreativeItemControl#1]
when update for paper 1.21?

**Comment by mrfloris** [comment]
5.4.0 has been released, I don't know if this now supports 1.21 items yml yet, but you could give it a try.

**Comment by Incluuu** [comment]
> 5.4.0 has been released, I don't know if this now supports 1.21 items yml yet, but you could give it a try.

I can't get anything out of gamemode creative, only the egg

I have to add all default permissions for it to work... why?

Grants access to items from the redstone tab in the creative menu.
Permission: creativeitemcontrol.menu.tools_&_utilities (>=1.19.3)
Default: true

[LP] Running LuckPerms v5.4.131

![image](https://github.com/user-attachments/assets/984f2243-28af-4929-b889-8221cf6bdb37)

**Comment by vk2gpz** [comment]
> > 5.4.0 has been released, I don't know if this now supports 1.21 items yml yet, but you could give it a try.
> 
> I can't get anything out of gamemode creative, only the egg
> 
> I have to add all default permissions for it to work... why?
> 
> Grants access to items from the redstone tab in the creative menu. Permission: creativeitemcontrol.menu.tools_&_utilities (>=1.19.3) Default: true
> 
> [LP] Running LuckPerms v5.4.131
> 
> ![image](https://private-user-images.githubusercontent.com/67196311/363404563-984f2243-28af-4929-b889-8221cf6bdb37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMjcyMTQsIm5iZiI6MTcyNTIyNjkxNCwicGF0aCI6Ii82NzE5NjMxMS8zNjM0MDQ1NjMtOTg0ZjIyNDMtMjhhZi00OTI5LWI4ODktODIyMWNmNmJkYjM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDIxNDE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4MTQ3ODgyOGRlNjU3OWZlYTVhYmIyNGZjZGNlYzllZTVlYzQ0ODMzYTBjYTVkOThkYjE0MmMwODgwZjRmYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K0DLOrCCp-qcbCfgWc40_4l3sgJQuz93lcai7dWnaqw)

if you don't have default permission nodes, you can simply add them in your plugin.yml.
